[project]
name = "Lab2"
version = "0.1.0"
description = "Distributed information processing systems Lab 2"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.9",
    "networkx>=3.3",
]
